@startuml
skinparam shadowing false
skinparam defaultFontName xfonts-wqy
skinparam defaultFontName times
skinparam dpi 300
skinparam activity  {
    DiamondFontSize 14
    ArrowFontSize 14
    FontSize 14
}
autonumber

participant 用户 as User
participant 浏览器 as Browser
participant 服务端 as  Server
participant 用户业务 as UserService
participant 唯一ID生成 as Uid
database 数据库 as DB
database 文件存储 as OSS


activate User
User -> Browser ++: 输入信息
Browser -> Browser ++--: 校验信息合法性
Browser -> Server ++: 注册用户
Server -> UserService ++: 检查用户名是否存在
UserService -> DB ++: 查询用户名是否存在
alt 用户名存在
    UserService <-- DB : 用户名存在
    note left
    通知用户名已被占用
    end note
else 用户名不存在
    return 用户名不存在
    UserService -> Uid ++: 生成用户ID
    return 用户ID
    UserService -> OSS ++: 保存年龄段审核图片
    return 图片URL
    UserService -> DB ++: 创建用户
    return 成功
    return 返回系统分配的用户ID
    return 用户ID
    return 用户ID
end
deactivate User
@enduml